package fi.thl.termed.util;

public enum ErrorCode {

  SCHEME_ID_MISSING,
  SCHEME_ID_ILLEGAL,

  CLASS_SCHEME_ID_MISSING,
  CLASS_SCHEME_ID_INVALID,
  CLASS_SCHEME_ID_ILLEGAL,
  CLASS_ID_MISSING,
  CLASS_ID_INVALID,

  TEXT_ATTRIBUTE_DOMAIN_SCHEME_ID_MISSING,
  TEXT_ATTRIBUTE_DOMAIN_SCHEME_ID_INVALID,
  TEXT_ATTRIBUTE_DOMAIN_SCHEME_ID_ILLEGAL,
  TEXT_ATTRIBUTE_DOMAIN_ID_MISSING,
  TEXT_ATTRIBUTE_DOMAIN_ID_INVALID,
  TEXT_ATTRIBUTE_DOMAIN_ID_ILLEGAL,
  TEXT_ATTRIBUTE_ID_MISSING,
  TEXT_ATTRIBUTE_ID_ILLEGAL,

  REFERENCE_ATTRIBUTE_DOMAIN_SCHEME_ID_MISSING,
  REFERENCE_ATTRIBUTE_DOMAIN_SCHEME_ID_INVALID,
  REFERENCE_ATTRIBUTE_DOMAIN_SCHEME_ID_ILLEGAL,
  REFERENCE_ATTRIBUTE_DOMAIN_ID_MISSING,
  REFERENCE_ATTRIBUTE_DOMAIN_ID_INVALID,
  REFERENCE_ATTRIBUTE_DOMAIN_ID_ILLEGAL,
  REFERENCE_ATTRIBUTE_RANGE_SCHEME_ID_MISSING,
  REFERENCE_ATTRIBUTE_RANGE_SCHEME_ID_ILLEGAL,
  REFERENCE_ATTRIBUTE_RANGE_ID_MISSING,
  REFERENCE_ATTRIBUTE_RANGE_ID_ILLEGAL,
  REFERENCE_ATTRIBUTE_ID_MISSING,
  REFERENCE_ATTRIBUTE_ID_ILLEGAL,

  RESOURCE_SCHEME_ID_MISSING,
  RESOURCE_TYPE_ID_MISSING

}
