package fi.thl.termed.util;

public enum ErrorCode {

  SCHEME_ID_MISSING,
  SCHEME_ID_INVALID,
  SCHEME_ID_ILLEGAL,

  CLASS_SCHEME_ID_MISSING,
  CLASS_SCHEME_ID_INVALID,
  CLASS_SCHEME_ID_ILLEGAL,
  CLASS_ID_MISSING,
  CLASS_ID_INVALID,

  TEXT_ATTRIBUTE_SCHEME_ID_MISSING,
  TEXT_ATTRIBUTE_SCHEME_ID_INVALID,
  TEXT_ATTRIBUTE_SCHEME_ID_ILLEGAL,
  TEXT_ATTRIBUTE_ID_MISSING,
  TEXT_ATTRIBUTE_ID_INVALID,

}
